package:
  name: libhwloc
  version: 1.11.2

source:
  fn: hwloc-1.11.2.tar.bz2
  url: https://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.2.tar.bz2
  sha1: 3d68de060808f04349538be4e63cde501cd53b0a

about:
  home: https://www.open-mpi.org/projects/hwloc/
  license: BSD

# test:
#   files:
#     - test.c
