mkdir build
cd build

cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DLLVM_ENABLE_RTTI=1 \
  -DLLVM_ENABLE_TERMINFO=0 \
  -DLLVM_ENABLE_ASSERTIONS=1 \
  -DLLVM_INCLUDE_DOCS=0 \
  -DLLVM_INCLUDE_TESTS=0 \
  -DLLVM_INCLUDE_UTILS=0 \
  -DLLVM_INCLUDE_EXAMPLES=0 \
  -DLLVM_TARGETS_TO_BUILD="X86" \
  -DBUILD_SHARED_LIBS=1 \
  -DCMAKE_INSTALL_PREFIX=$PREFIX \
  ..

cmake --build . -- -j 8
cmake --build . --target install
