# Stolen from https://github.com/numba/llvmlite/tree/master/conda-recipes/llvmdev
package:
  name: akllvmdev
  version: "3.7.0"

source:
  fn: llvm-3.7.0.src.tar.xz
  url: http://llvm.org/releases/3.7.0/llvm-3.7.0.src.tar.xz
  sha1: 0355c2fe01a8d17c3315069e6f2ef80c281e7dad
  patches:
    # From http://reviews.llvm.org/D6052
    - ../llvm-elf-relocation.patch

build:
  number: 1

requirements:
  build:
    - system           [linux and not armv7l]
  run:
    - system           [linux and not armv7l]

test:
  commands:
    - llvm-config --libs   [linux]
    - llc -version         [linux]

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.6.0/LICENSE.TXT)
  summary: Development headers and libraries for LLVM
